### ISSUE TITLE
apply recipe whilst changing name of variable

### ISSUE THREAD

**Issue by annecori** [Hackout3/cleanr#1]
Hey Rich, 
sometimes it is useful to keep track of a variable as is, as well as a a recoded version of the variable, under a different name. 
At the moment it's easy to do that with cleanr if using a series of functions, e.g.: 

```
- Gender:
    from: DEMSEX
    recode_character:
      table:
        "Female": "F"
        "Male": "M"
        "Missing": !missing
      unmatched_action: "error"
```

 but not (as far as I'm aware) if using a recipe, e.g.: 

```
- DEMAGE_RECODED: 
    from: DEMAGE
    !recipe NumericalMissedSkipped 
```

Is there any chance you could look into this? 
Thanks!

Anne
